workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"

image: gitlab-registry.cern.ch/ml_l1/${MODEL_NAME}:Prod

stages:
  - load
  - preprocess
  - train
  - validate
  - compile
  - triggermodel

.before_ml:
  before_script:
    - source activate training-gpu
    - echo "${EOSPASS}" | kinit "${EOSUSER}@CERN.CH"
    - cd ${MODEL_NAME}

load_data:
  extends: .before_ml
  stage: load
  tags: [CPU-INTENSIVE]
  script:
    - kedro run --pipeline=load_data --params run_name=${RUN_NAME}_load_data
  artifacts:
    paths:
      - ${MODEL_NAME}/data/02_loaded/

preprocess_data:
  extends: .before_ml
  stage: preprocess
  needs: [load_data]
  tags: [CPU-INTENSIVE]
  script:
    - kedro run --pipeline=data_processing --params run_name=${RUN_NAME}_process_data
  artifacts:
    paths:
      - ${MODEL_NAME}/data/03_preprocessed/

train_model:
  extends: .before_ml
  stage: train
  needs: [preprocess_data]
  tags: [NVIDIA-H100-NVL]
  script:
    - kedro run --pipeline=model_training --params run_name=${RUN_NAME}_train_model
  artifacts:
    paths:
      - ${MODEL_NAME}/data/04_models/

validate_model:
  extends: .before_ml
  stage: validate
  needs: [preprocess_data, train_model]
  tags: [k8s-eos]
  script:
    - kedro run --pipeline=model_validation --params run_name=${RUN_NAME}_validate_model
  artifacts:
    paths:
      - ${MODEL_NAME}/data/05_validation/

compile:
  extends: .before_ml
  stage: compile
  needs: [preprocess_data, train_model, validate_model]
  tags: [k8s-eos]
  script:
    - export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
    - kedro run --pipeline=compile --params run_name=${RUN_NAME}_compile_model
  artifacts:
    when: always
    paths:
      - ${MODEL_NAME}/data/06_compile/

build_fw:
  stage: triggermodel
  image: registry.cern.ch/ci4fpga/vivado:2024.1
  tags: [fpga-mid]
  needs: [compile]
  script:
    - cd ${MODEL_NAME}/triggermodel/firmware/firmware/
    - TCL_FILE=$(find . -maxdepth 2 -name "*.tcl" | head -n 1)
    - vitis_hls -f "$TCL_FILE"
  artifacts:
    paths:
      - ${MODEL_NAME}/triggermodel/firmware/
