apiVersion: batch/v1
kind: Job
metadata:
  name: embed-job
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - "Tesla-V100-SXM2-32GB"
                  - "NVIDIA-A100-PCIE-40GB"
                  - "NVIDIA-RTX-A6000"
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/mquinnan/axol1tl-hub:axol1tl-container
        # Use a shell script to chain your commands
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "Cloning repository..."
            git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/ellisonscheuller/challenge9.git
            cd challenge9/

            echo "Installing dependencies..."
            pip3 install .
            pip3 install wandb
            
            echo "Starting training..."
            python3 train.py \
              --data_cfg=/embedvol/configs/data_config_smcocktail.yaml \
              --train_cfg=/embedvol/configs/train_config_hlt.yaml \
              --data=/embedvol/embedding_hlt_smcocktail_train.pt \
              --degraded_data=/embedvol/embedding_hlt_smcocktail_train_degraded.pt \
              --outdir=/embedvol/ \
              --test_mode
        env:
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb-secrets
                key: WANDB_API_KEY
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-secrets
                key: GIT_TOKEN
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: github-secrets
                key: GIT_USER
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 32Gi
            cpu: 8
          requests:
            nvidia.com/gpu: 1
            memory: 32Gi
            cpu: 8
        volumeMounts:
        - mountPath: /embedvol
          name: embedvol
      restartPolicy: OnFailure 
      volumes:
        - name: embedvol
          persistentVolumeClaim:
            claimName: embedvol
      tolerations:
        - key: "nautilus.io/axol1tl"
          operator: "Exists"
          effect: "NoSchedule"
  backoffLimit: 2 